### ISSUE TITLE
New Discord Bot Client pls

### ISSUE THREAD

**Issue by maechtische** [Flam3rboy/Flam3rboy#2]
Flam3rboy bitte mach einen neuen discord bot client. Flam3rboy pls make a new discord bot client

**Comment by hadmesa** [comment]
Yeah. Please make a New. The old one doesnt work

**Comment by hadmesa** [comment]
@Flam3rboy

**Comment by hadmesa** [comment]
.

**Comment by Fruityisgood** [comment]
He said he won't fix it anymore but he is working on [Fosscord](https://fosscord.com)
